export const EVENT_ROLES = [
  {
    id: 'usher',
    title: 'Usher',
    description: 'Guide guests, manage seating, and ensure smooth event flow',
    icon: '👔',
    hiredThisMonth: 3,
    interviewQuestions: [
      'Tell me about your experience as an usher or guiding people at events',
      'How do you handle difficult or confused guests?',
      'Describe a time you had to manage a large crowd',
      'What do you think makes a great usher?',
      'Are you comfortable standing for long periods and working weekends?',
    ],
  },
  {
    id: 'bartender',
    title: 'Bartender',
    description: 'Mix drinks, serve guests, and maintain bar area',
    icon: '🍸',
    hiredThisMonth: 2,
    interviewQuestions: [
      'What\'s your bartending experience? How long have you been doing this?',
      'What types of cocktails and drinks can you make?',
      'How do you handle a busy bar with many orders at once?',
      'Tell me about your customer service approach',
      'Do you have any certifications or formal training?',
    ],
  },
  {
    id: 'dj',
    title: 'DJ / Music Performer',
    description: 'Provide music entertainment and control event atmosphere',
    icon: '🎧',
    hiredThisMonth: 1,
    interviewQuestions: [
      'What genres of music do you specialize in?',
      'What equipment do you use for performances?',
      'Tell me about a memorable event you\'ve DJ\'d',
      'How do you read the crowd and adjust your set?',
      'Do you have your own equipment or need rentals?',
    ],
  },
  {
    id: 'security',
    title: 'Security / Bouncer',
    description: 'Maintain safety, control access, and handle security issues',
    icon: '🛡️',
    hiredThisMonth: 2,
    interviewQuestions: [
      'What\'s your experience in security or crowd control?',
      'How do you handle aggressive or intoxicated guests?',
      'Do you have any security training or certifications?',
      'Describe a challenging security situation you managed',
      'Are you comfortable working late nights and handling conflicts?',
    ],
  },
  {
    id: 'stage_crew',
    title: 'Stage Crew / Setup',
    description: 'Set up equipment, manage technical aspects, and assist performers',
    icon: '🔧',
    hiredThisMonth: 1,
    interviewQuestions: [
      'What\'s your experience with stage setup and equipment?',
      'What types of equipment are you familiar with?',
      'How do you handle technical problems during an event?',
      'Tell me about your teamwork experience',
      'Are you comfortable with physical work and lifting?',
    ],
  },
  {
    id: 'photographer',
    title: 'Photographer / Videographer',
    description: 'Capture event moments through photos and videos',
    icon: '📸',
    hiredThisMonth: 1,
    interviewQuestions: [
      'What\'s your photography/videography experience?',
      'What equipment and software do you use?',
      'Show me examples of events you\'ve covered',
      'How do you handle low-light or challenging conditions?',
      'What\'s your turnaround time for delivering edited content?',
    ],
  },
  {
    id: 'nanny',
    title: 'Nanny / Childcare',
    description: 'Supervise and care for children during events',
    icon: '👶',
    hiredThisMonth: 0,
    interviewQuestions: [
      'What\'s your experience caring for children?',
      'What age groups are you most comfortable with?',
      'How do you handle emergencies or difficult behavior?',
      'Do you have any childcare certifications or first aid training?',
      'Tell me about a challenging childcare situation you handled',
    ],
  },
  {
    id: 'host',
    title: 'MC / Event Host',
    description: 'Emcee events, make announcements, and engage audience',
    icon: '🎤',
    hiredThisMonth: 1,
    interviewQuestions: [
      'What\'s your experience as an MC or event host?',
      'What types of events have you hosted?',
      'How do you handle unexpected situations or technical issues?',
      'Tell me about your public speaking skills',
      'Can you adapt your style for different audiences?',
    ],
  },
  {
    id: 'server',
    title: 'Server / Waitstaff',
    description: 'Serve food and drinks, clear tables, and assist guests',
    icon: '🍽️',
    hiredThisMonth: 0,
    interviewQuestions: [
      'What\'s your serving experience at events or restaurants?',
      'How do you handle multiple tables or large groups?',
      'Tell me about your customer service approach',
      'How do you deal with difficult guests or complaints?',
      'Are you comfortable carrying trays and working on your feet?',
    ],
  },
  {
    id: 'comedian',
    title: 'Stand-up Comedian',
    description: 'Provide comedy entertainment for events',
    icon: '😄',
    hiredThisMonth: 0,
    interviewQuestions: [
      'How long have you been doing stand-up comedy?',
      'What\'s your comedy style and typical set length?',
      'Tell me about venues or events you\'ve performed at',
      'How do you handle tough crowds or hecklers?',
      'Do you have video samples of your performances?',
    ],
  },
  {
    id: 'vendor_food',
    title: 'Food Vendor',
    description: 'Prepare and sell food at events',
    icon: '🍔',
    hiredThisMonth: 0,
    interviewQuestions: [
      'What type of food do you specialize in?',
      'What\'s your experience vending at events?',
      'Do you have proper food handling certifications?',
      'What equipment do you need for your setup?',
      'How do you handle high-volume orders during peak times?',
    ],
  },
  {
    id: 'vendor_drinks',
    title: 'Drink Vendor',
    description: 'Prepare and sell beverages at events',
    icon: '🥤',
    hiredThisMonth: 0,
    interviewQuestions: [
      'What types of drinks do you offer?',
      'What\'s your experience at event vending?',
      'Do you have any required licenses or permits?',
      'What equipment do you bring for your setup?',
      'How do you keep drinks cold and fresh during events?',
    ],
  },
] as const;

export type RoleId = typeof EVENT_ROLES[number]['id'];
